#include "a_opencl_source_map.hpp" 
namespace mllm::opencl { 
const char* flash_attention = 
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"// FlashAttention v1 (Dao et al.,2022),forward pass for inference.\n"
"// Same paper algorithm (K/V tiled in __local,online softmax merge with running\n"
"// (m_i,l_i,O_i) per Q row),but with a redesigned thread mapping for OpenCL:\n"
"//\n"
"// local_size=FA_D (= head_dim,e.g. 128 for Qwen3)\n"
"// threads 0..(FA_BR*FA_BC-1) → compute S[i][c]=Q_i . K_c serially\n"
"// (one thread per S element,NO tree reduce)\n"
"// threads 0..(FA_D-1) → compute pv=sum_c P[i][c]*V_local[c][d]\n"
"// (one thread per d-position; serial loop in c)\n"
"//\n"
"// This kills the per-S-element tree reduction barriers that dominated the\n"
"// previous implementation: ~3 barriers per j-iter total (load/S/end-of-j)\n"
"// instead of ~580.\n"
"//\n"
"// Layout: BHSD (all input tensors may be non-contiguous; strides passed in).\n"
"// Output O is contiguous BHSD.\n"
"#ifndef FA_BR\n"
"#define FA_BR 4\n"
"#endif\n"
"#ifndef FA_BC\n"
"#define FA_BC 16\n"
"#endif\n"
"#ifndef FA_D\n"
"#define FA_D 128\n"
"#endif\n"
"#define FA_S_THREADS (FA_BR*FA_BC) //=64 active threads during S compute\n"
"// ---------------------------------------------------------------- fp32\n"
"__kernel void flash_attention_fp32(\n"
" __global const float *Q,__global const float *K,__global const float *V,\n"
" __global float *O,\n"
" const int B,const int H,const int S_q,const int S_kv,const int D,\n"
" const int Q_b_stride,const int Q_h_stride,const int Q_s_stride,\n"
" const int K_b_stride,const int K_h_stride,const int K_s_stride,\n"
" const int V_b_stride,const int V_h_stride,const int V_s_stride,\n"
" const float scale,const int causal_mask) {\n"
" const int t=get_local_id(0); // 0..FA_D-1\n"
" const int q_block=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" if (bh >= B*H) return;\n"
" const int q_row_start=q_block*FA_BR;\n"
" if (q_row_start >= S_q) return;\n"
" const int b=bh/H;\n"
" const int h=bh-b*H;\n"
" const int q_h_off=b*Q_b_stride+h*Q_h_stride;\n"
" const int k_h_off=b*K_b_stride+h*K_h_stride;\n"
" const int v_h_off=b*V_b_stride+h*V_h_stride;\n"
" const int o_h_off=bh*S_q*D;\n"
" __local float Q_local[FA_BR*FA_D];\n"
" __local float K_local[FA_BC*FA_D];\n"
" __local float V_local[FA_BC*FA_D];\n"
" __local float S_local[FA_BR*FA_BC];\n"
" __local float m_il[FA_BR];\n"
" __local float l_il[FA_BR];\n"
" // Load Q tile (B_r × D) — each thread (= d-position) loads B_r elements.\n"
" for (int i=0; i<FA_BR; ++i) {\n"
" const int q_row=q_row_start+i;\n"
" Q_local[i*FA_D+t] =\n"
" (q_row<S_q) ? Q[q_h_off+q_row*Q_s_stride+t] : 0.0f;\n"
" }\n"
" // Init per-Q-row running stats (only first FA_BR threads write).\n"
" if (t<FA_BR) {\n"
" m_il[t]=-INFINITY;\n"
" l_il[t]=0.0f;\n"
" }\n"
" // O accumulator in private registers: one float per Q row at this thread's d.\n"
" float o_priv[FA_BR];\n"
" for (int i=0; i<FA_BR; ++i) o_priv[i]=0.0f;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // Outer loop over K/V blocks (paper Algorithm 1,line 5).\n"
" for (int j_start=0; j_start<S_kv; j_start += FA_BC) {\n"
" // Load K_j,V_j tiles cooperatively (each thread loads B_c elements).\n"
" for (int c=0; c<FA_BC; ++c) {\n"
" const int k_row=j_start+c;\n"
" if (k_row<S_kv) {\n"
" K_local[c*FA_D+t]=K[k_h_off+k_row*K_s_stride+t];\n"
" V_local[c*FA_D+t]=V[v_h_off+k_row*V_s_stride+t];\n"
" } else {\n"
" K_local[c*FA_D+t]=0.0f;\n"
" V_local[c*FA_D+t]=0.0f;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // S_ij=Q_i K_j^T. Each S element computed by ONE thread doing a serial\n"
" // 128-element dot product in registers. NO tree reduction,NO per-element\n"
" // barriers. Threads with t >= FA_S_THREADS idle this phase.\n"
" if (t<FA_S_THREADS) {\n"
" const int i=t/FA_BC;\n"
" const int c=t-i*FA_BC;\n"
" float acc=0.0f;\n"
" for (int d=0; d<FA_D; ++d) {\n"
" acc += Q_local[i*FA_D+d]*K_local[c*FA_D+d];\n"
" }\n"
" const int q_row=q_row_start+i;\n"
" const int k_row=j_start+c;\n"
" const int q_pos=S_kv-S_q+q_row;\n"
" if (q_row >= S_q || k_row >= S_kv ||\n"
" (causal_mask && k_row>q_pos)) {\n"
" acc=-INFINITY;\n"
" } else {\n"
" acc *= scale;\n"
" }\n"
" S_local[i*FA_BC+c]=acc;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // Online softmax merge per Q row. All threads compute the same scalars\n"
" // (m_tilde,l_tilde,m_new,...); pv is the only per-d quantity.\n"
" for (int i=0; i<FA_BR; ++i) {\n"
" float m_tilde=-INFINITY;\n"
" for (int c=0; c<FA_BC; ++c) {\n"
" m_tilde=fmax(m_tilde,S_local[i*FA_BC+c]);\n"
" }\n"
" float l_tilde=0.0f;\n"
" float pv=0.0f;\n"
" for (int c=0; c<FA_BC; ++c) {\n"
" const float s=S_local[i*FA_BC+c];\n"
" const float p=(s == -INFINITY) ? 0.0f : exp(s-m_tilde);\n"
" l_tilde += p;\n"
" pv += p*V_local[c*FA_D+t];\n"
" }\n"
" const float m_old=m_il[i];\n"
" const float l_old=l_il[i];\n"
" const float m_new=fmax(m_old,m_tilde);\n"
" const float a=(m_old == -INFINITY) ? 0.0f : exp(m_old-m_new);\n"
" const float bb=(m_tilde == -INFINITY) ? 0.0f : exp(m_tilde-m_new);\n"
" const float l_new=a*l_old+bb*l_tilde;\n"
" o_priv[i] =\n"
" (l_new>0.0f) ? (l_old*a*o_priv[i]+bb*pv)/l_new : 0.0f;\n"
" if (t == 0) {\n"
" m_il[i]=m_new;\n"
" l_il[i]=l_new;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" // Write O (one float per (q_row,d) for this thread).\n"
" for (int i=0; i<FA_BR; ++i) {\n"
" const int q_row=q_row_start+i;\n"
" if (q_row<S_q) { O[o_h_off+q_row*D+t]=o_priv[i]; }\n"
" }\n"
"}\n"
"// ---------------------------------------------------------------- fp16 (optimized)\n"
"//\n"
"// Optimized vs the fp32 reference above,applying lessons from the tuned OpenCL\n"
"// GEMM/GEMV kernels. The fp32 kernel is left untouched as the numeric reference.\n"
"//\n"
"// FA_BR_H q-rows per workgroup (default 8 — the host must launch q_blocks =\n"
"// ceil(S_q/FA_BR_H) for fp16); FA_BC_H=FA_D/4 keys per K/V tile. With\n"
"// FA_BR_H=8,D=128 → FA_BC_H=32 and FA_BR_H*FA_BC_H=256=2*FA_D,so each\n"
"// of the 128 lanes computes TWO S elements in QK^T (two Q rows i0 and i0+4\n"
"// sharing column c → the K[c] row is loaded once and reused → cross-q reuse,\n"
"// and the per-j-iter load+barrier overhead is amortized over 2x the rows).\n"
"//\n"
"// Other techniques: native-half LDS storage; transposed-V LDS tile for\n"
"// contiguous vectorized P·V; hoisted producer-lane softmax (native_exp);\n"
"// half8-vectorized QK^T dot; causal block-skip of fully-masked K/V blocks.\n"
"//\n"
"// PRECISION INVARIANT: storage+multiply operands are half; ALL accumulators\n"
"// (QK^T dot,P·V sum,o_priv across the whole S_kv loop) and softmax stats\n"
"// (m,l,a,bb,l_new) stay fp32 — they feed exp(). Requires FA_D % 4 == 0 and\n"
"// FA_BR_H*FA_BC_H == 2*FA_D (true for FA_BR_H=8,any D divisible by 4).\n"
"#ifndef FA_BR_H\n"
"#define FA_BR_H 8\n"
"#endif\n"
"#define FA_BC_H (FA_D/4) // 32 for D=128\n"
"#define FA_ROWSTEP (FA_D/FA_BC_H) // 4: rows handled by a lane are i0+s*ROWSTEP\n"
"#define FA_NSPL (FA_BR_H*FA_BC_H/FA_D) // S elements per lane (2 for BR=8,4 for BR=16)\n"
"__kernel void flash_attention_fp16(\n"
" __global const half *Q,__global const half *K,__global const half *V,\n"
" __global half *O,\n"
" const int B,const int H,const int S_q,const int S_kv,const int D,\n"
" const int Q_b_stride,const int Q_h_stride,const int Q_s_stride,\n"
" const int K_b_stride,const int K_h_stride,const int K_s_stride,\n"
" const int V_b_stride,const int V_h_stride,const int V_s_stride,\n"
" const float scale,const int causal_mask) {\n"
" const int t=get_local_id(0); // 0..FA_D-1\n"
" const int q_block=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" if (bh >= B*H) return;\n"
" const int q_row_start=q_block*FA_BR_H;\n"
" if (q_row_start >= S_q) return;\n"
" // Valid rows in this workgroup (< FA_BR_H only for the last block/decode).\n"
" // A uniform loop bound (not a per-iter `continue`) keeps the compiler's loop\n"
" // optimization for full blocks while letting decode (S_q=1) skip the waste.\n"
" const int nrows=min(FA_BR_H,S_q-q_row_start);\n"
" const int b=bh/H;\n"
" const int h=bh-b*H;\n"
" const int q_h_off=b*Q_b_stride+h*Q_h_stride;\n"
" const int k_h_off=b*K_b_stride+h*K_h_stride;\n"
" const int v_h_off=b*V_b_stride+h*V_h_stride;\n"
" const int o_h_off=bh*S_q*D;\n"
" __local half Q_local[FA_BR_H*FA_D];\n"
" __local half K_local[FA_BC_H*FA_D]; // c-major [c*D+d] for the QK^T dot\n"
" __local half V_localT[FA_D*FA_BC_H]; // TRANSPOSED [d*FA_BC_H+c] for P·V\n"
" __local float S_local[FA_BR_H*FA_BC_H]; // scores (fp32)\n"
" __local float m_il[FA_BR_H];\n"
" __local float l_il[FA_BR_H];\n"
" __local float sh_a[FA_BR_H];\n"
" __local float sh_bb[FA_BR_H];\n"
" __local float sh_lold[FA_BR_H];\n"
" __local float sh_lnew[FA_BR_H];\n"
" for (int i=0; i<FA_BR_H; ++i) {\n"
" const int q_row=q_row_start+i;\n"
" Q_local[i*FA_D+t] =\n"
" (q_row<S_q) ? Q[q_h_off+q_row*Q_s_stride+t] : (half)0;\n"
" }\n"
" if (t<FA_BR_H) {\n"
" m_il[t]=-INFINITY;\n"
" l_il[t]=0.0f;\n"
" }\n"
" float o_priv[FA_BR_H];\n"
" for (int i=0; i<FA_BR_H; ++i) o_priv[i]=0.0f;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // Causal block-skip: cap the j-loop at this q_block's last diagonal block.\n"
" int j_max=S_kv;\n"
" if (causal_mask) {\n"
" const int last_q_pos=S_kv-S_q+(q_row_start+FA_BR_H-1);\n"
" j_max=min(S_kv,last_q_pos+1);\n"
" }\n"
" for (int j_start=0; j_start<j_max; j_start += FA_BC_H) {\n"
" for (int c=0; c<FA_BC_H; ++c) {\n"
" const int k_row=j_start+c;\n"
" if (k_row<S_kv) {\n"
" K_local[c*FA_D+t]=K[k_h_off+k_row*K_s_stride+t];\n"
" V_localT[t*FA_BC_H+c]=V[v_h_off+k_row*V_s_stride+t];\n"
" } else {\n"
" K_local[c*FA_D+t]=(half)0;\n"
" V_localT[t*FA_BC_H+c]=(half)0;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // QK^T — each of the 128 lanes computes TWO S elements: rows i0 and\n"
" // i0+FA_ROWSTEP at the same column c,sharing the K[c] row load. Invalid\n"
" // (masked/out-of-range) rows are gated out so partial blocks (e.g. decode\n"
" // S_q=1 under FA_BR_H=8) don't pay for the wasted rows.\n"
" {\n"
" const int c=t % FA_BC_H;\n"
" const int i0=t/FA_BC_H;\n"
" const int k_row=j_start+c;\n"
" __local const half* krow=K_local+c*FA_D;\n"
" float8 acc[FA_NSPL];\n"
" #pragma unroll\n"
" for (int s=0; s<FA_NSPL; ++s) acc[s]=(float8)(0.0f);\n"
" for (int d8=0; d8<FA_D/8; ++d8) {\n"
" float8 kf=convert_float8(vload8(d8,krow)); // shared K row across rows\n"
" #pragma unroll\n"
" for (int s=0; s<FA_NSPL; ++s) {\n"
" acc[s] += convert_float8(vload8(d8,Q_local+(i0+s*FA_ROWSTEP)*FA_D))*kf;\n"
" }\n"
" }\n"
" #pragma unroll\n"
" for (int s=0; s<FA_NSPL; ++s) {\n"
" const int i=i0+s*FA_ROWSTEP;\n"
" const int qr=q_row_start+i;\n"
" const int qp=S_kv-S_q+qr;\n"
" const float8 a=acc[s];\n"
" const float v=a.s0+a.s1+a.s2+a.s3+a.s4+a.s5+a.s6+a.s7;\n"
" S_local[i*FA_BC_H+c] =\n"
" (qr >= S_q || k_row >= S_kv || (causal_mask && k_row>qp)) ? -INFINITY : v*scale;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // Online softmax — hoisted: one producer lane per valid Q row. Vectorized\n"
" // max/exp/sum over c (native_exp on float8). Masked entries are -INF;\n"
" // select() forces their prob to 0 (don't trust native_exp(-INF)).\n"
" if (t<nrows) {\n"
" const int i=t;\n"
" __local float* prow=S_local+i*FA_BC_H; // aliased: scores in,probs out\n"
" float8 m8=(float8)(-INFINITY);\n"
" for (int c8=0; c8<FA_BC_H/8; ++c8) m8=fmax(m8,vload8(c8,prow));\n"
" float4 m4=fmax(m8.lo,m8.hi);\n"
" float2 m2=fmax(m4.lo,m4.hi);\n"
" float m_tilde=fmax(m2.s0,m2.s1);\n"
" float8 l8=(float8)(0.0f);\n"
" for (int c8=0; c8<FA_BC_H/8; ++c8) {\n"
" const float8 s8=vload8(c8,prow);\n"
" const float8 p8=select(native_exp(s8-m_tilde),(float8)(0.0f),isinf(s8));\n"
" vstore8(p8,c8,prow);\n"
" l8 += p8;\n"
" }\n"
" float4 l4=l8.lo+l8.hi;\n"
" float2 l2=l4.lo+l4.hi;\n"
" float l_tilde=l2.s0+l2.s1;\n"
" const float m_old=m_il[i];\n"
" const float l_old=l_il[i];\n"
" const float m_new=fmax(m_old,m_tilde);\n"
" const float a=(m_old == -INFINITY) ? 0.0f : native_exp(m_old-m_new);\n"
" const float bb=(m_tilde == -INFINITY) ? 0.0f : native_exp(m_tilde-m_new);\n"
" const float l_new=a*l_old+bb*l_tilde;\n"
" sh_a[i]=a;\n"
" sh_bb[i]=bb;\n"
" sh_lold[i]=l_old;\n"
" sh_lnew[i]=l_new;\n"
" m_il[i]=m_new;\n"
" l_il[i]=l_new;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // P·V+O rescale — ALL lanes: lane t owns d=t; FA_BR_H rows,vectorized in c.\n"
" {\n"
" __local const half* vrow=V_localT+t*FA_BC_H;\n"
" for (int i=0; i<nrows; ++i) {\n"
" __local const float* prow=S_local+i*FA_BC_H;\n"
" float8 pv8=(float8)(0.0f);\n"
" for (int c8=0; c8<FA_BC_H/8; ++c8) {\n"
" pv8 += vload8(c8,prow)*convert_float8(vload8(c8,vrow));\n"
" }\n"
" const float pv=pv8.s0+pv8.s1+pv8.s2+pv8.s3 +\n"
" pv8.s4+pv8.s5+pv8.s6+pv8.s7;\n"
" const float a=sh_a[i],bb=sh_bb[i];\n"
" const float l_old=sh_lold[i],l_new=sh_lnew[i];\n"
" o_priv[i] =\n"
" (l_new>0.0f) ? (l_old*a*o_priv[i]+bb*pv)/l_new : 0.0f;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" for (int i=0; i<nrows; ++i) {\n"
" O[o_h_off+(q_row_start+i)*D+t]=(half)o_priv[i];\n"
" }\n"
"}\n"
"// ---------------------------------------------------------------- fp16 decode (S_q == 1)\n"
"//\n"
"// Dedicated decode kernel: at S_q=1 each K/V element is used exactly ONCE,so\n"
"// the prefill kernel's global->LDS K/V staging is pure overhead and its\n"
"// (q-rows x keys) lane mapping wastes 3/4 of the QK lanes. This kernel streams\n"
"// K/V straight from global with no K/V LDS tiles:\n"
"//\n"
"// score phase: lane t owns key row (bs+t) -> full D-dot in registers,no\n"
"// cross-lane reduction. Across a wave the row base addresses\n"
"// stride by D*2 bytes,but each lane walks its row sequentially\n"
"// (vload8),so every touched cache line is fully consumed --\n"
"// the L1/UCHE absorbs the interleave (verified GEMV-style).\n"
"// softmax: one producer lane per block,float8-vectorized,online (m,l)\n"
"// with the rescale factor a broadcast via LDS.\n"
"// P*V phase: lane t owns output dim d=t; V rows read straight from global,\n"
"// coalesced across lanes; probs broadcast from LDS.\n"
"//\n"
"// 3 barriers per FA_D-key block (vs 4 per FA_BC_H=32 keys in the prefill\n"
"// kernel=~5x fewer per key),zero wasted dot lanes.\n"
"//\n"
"// Split-K (flash-decoding): grid dim1=nsplit partitions over S_kv. Each\n"
"// workgroup writes an UNNORMALIZED partial (o_acc scaled to its running max,\n"
"// plus m,l) to `partial` [B*H,nsplit,FA_D+2] (float); the merge kernel\n"
"// below combines partitions. With nsplit == 1 the kernel normalizes and\n"
"// writes O directly (no scratch,no merge launch).\n"
"//\n"
"// S_q==1 makes the causal mask a no-op (every key index <= S_kv-1=q_pos),\n"
"// so no mask test is needed. Accumulators and softmax stats stay fp32.\n"
"__kernel void flash_attention_fp16_decode(\n"
" __global const half *Q,__global const half *K,__global const half *V,\n"
" __global half *O,__global float *partial,\n"
" const int B,const int H,const int S_kv,const int D,\n"
" const int Q_b_stride,const int Q_h_stride,\n"
" const int K_b_stride,const int K_h_stride,const int K_s_stride,\n"
" const int V_b_stride,const int V_h_stride,const int V_s_stride,\n"
" const float scale,const int nsplit,const int span) {\n"
" const int t=get_local_id(0); // 0..FA_D-1\n"
" const int split=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" if (bh >= B*H) return;\n"
" const int b=bh/H;\n"
" const int h=bh-b*H;\n"
" const int q_off=b*Q_b_stride+h*Q_h_stride;\n"
" const int k_h_off=b*K_b_stride+h*K_h_stride;\n"
" const int v_h_off=b*V_b_stride+h*V_h_stride;\n"
" const int kv_begin=split*span;\n"
" const int kv_end=min(S_kv,kv_begin+span);\n"
" const int pbase=(bh*nsplit+split)*(FA_D+2);\n"
" if (kv_begin >= kv_end) { // empty partition: still write a neutral partial\n"
" if (nsplit>1) {\n"
" partial[pbase+t]=0.0f;\n"
" if (t == 0) {\n"
" partial[pbase+FA_D]=-INFINITY;\n"
" partial[pbase+FA_D+1]=0.0f;\n"
" }\n"
" }\n"
" return;\n"
" }\n"
" __local half Q_l[FA_D];\n"
" __local float S_l[FA_D]; // one block of scores -> probs (in place)\n"
" __local float sh_a; // per-block rescale factor exp(m_old-m_new)\n"
" Q_l[t]=Q[q_off+t];\n"
" float o_acc=0.0f; // lane t's UNNORMALIZED output dim d=t\n"
" float m_run=-INFINITY; // tracked by lane 0 (authoritative)\n"
" float l_run=0.0f;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int bs=kv_begin; bs<kv_end; bs += FA_D) {\n"
" const int blk_n=min(FA_D,kv_end-bs);\n"
" // ---- scores: lane t -> key row bs+t (full-depth dot,fp32 accumulate)\n"
" {\n"
" float s=-INFINITY;\n"
" if (t<blk_n) {\n"
" __global const half *krow=K+k_h_off+(long)(bs+t)*K_s_stride;\n"
" float8 acc=(float8)(0.0f);\n"
" #pragma unroll\n"
" for (int d8=0; d8<FA_D/8; ++d8) {\n"
" acc += convert_float8(vload8(d8,Q_l))*convert_float8(vload8(d8,krow));\n"
" }\n"
" s=(acc.s0+acc.s1+acc.s2+acc.s3 +\n"
" acc.s4+acc.s5+acc.s6+acc.s7)*scale;\n"
" }\n"
" S_l[t]=s;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // ---- online softmax: producer lane 0,float8-vectorized over the block\n"
" // (FA_DEC_PROF ablation: 1=scores only,2=+softmax,3/unset=full)\n"
"#if defined(FA_DEC_PROF) && FA_DEC_PROF<2\n"
" if (t == 0) { sh_a=S_l[t]; m_run=fmax(m_run,S_l[0]); l_run += 1.0f; }\n"
"#else\n"
" if (t == 0) {\n"
" float8 m8=(float8)(-INFINITY);\n"
" for (int c8=0; c8<FA_D/8; ++c8) m8=fmax(m8,vload8(c8,S_l));\n"
" float4 m4=fmax(m8.lo,m8.hi);\n"
" float2 m2=fmax(m4.lo,m4.hi);\n"
" const float m_tilde=fmax(m2.s0,m2.s1);\n"
" const float m_new=fmax(m_run,m_tilde);\n"
" const float a=(m_run == -INFINITY) ? 0.0f : native_exp(m_run-m_new);\n"
" float8 l8=(float8)(0.0f);\n"
" for (int c8=0; c8<FA_D/8; ++c8) {\n"
" const float8 s8=vload8(c8,S_l);\n"
" const float8 p8=select(native_exp(s8-m_new),(float8)(0.0f),isinf(s8));\n"
" vstore8(p8,c8,S_l);\n"
" l8 += p8;\n"
" }\n"
" float4 l4=l8.lo+l8.hi;\n"
" float2 l2=l4.lo+l4.hi;\n"
" l_run=a*l_run+(l2.s0+l2.s1);\n"
" m_run=m_new;\n"
" sh_a=a;\n"
" }\n"
"#endif\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // ---- P*V: lane t=output dim t; V coalesced across lanes\n"
"#if defined(FA_DEC_PROF) && FA_DEC_PROF<3\n"
" o_acc += sh_a+S_l[t & (FA_D-1)]; // keep prior phases live,skip PV\n"
"#else\n"
" {\n"
" const float a=sh_a;\n"
" float pv=0.0f;\n"
" __global const half *vbase=V+v_h_off+(long)bs*V_s_stride+t;\n"
" #pragma unroll 8\n"
" for (int c=0; c<blk_n; ++c) {\n"
" pv += S_l[c]*(float)vbase[(long)c*V_s_stride];\n"
" }\n"
" o_acc=o_acc*a+pv;\n"
" }\n"
"#endif\n"
" barrier(CLK_LOCAL_MEM_FENCE); // S_l reused next block\n"
" }\n"
" if (nsplit == 1) {\n"
" // Single partition: normalize and write O directly (skip scratch+merge).\n"
" // l_run is authoritative on lane 0 only -> broadcast via LDS (reuse sh_a).\n"
" if (t == 0) sh_a=l_run;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" const float l_all=sh_a;\n"
" O[bh*FA_D+t]=(half)((l_all>0.0f) ? o_acc/l_all : 0.0f);\n"
" } else {\n"
" partial[pbase+t]=o_acc;\n"
" if (t == 0) {\n"
" partial[pbase+FA_D]=m_run;\n"
" partial[pbase+FA_D+1]=l_run;\n"
" }\n"
" }\n"
"}\n"
"// Merge nsplit partials -> O. Dispatch: global (FA_D,1,B*H),local (FA_D,1,1).\n"
"// partial layout: [B*H,nsplit,FA_D+2] float; slot FA_D=m,FA_D+1=l.\n"
"// Standard flash-decoding merge: O=sum_s w_s*o_s/sum_s w_s*l_s with\n"
"// w_s=exp(m_s-max_s m_s); empty partitions (m=-inf) contribute 0.\n"
"__kernel void flash_attention_fp16_decode_merge(\n"
" __global const float *partial,__global half *O,\n"
" const int B,const int H,const int nsplit) {\n"
" const int t=get_local_id(0);\n"
" const int bh=get_global_id(2);\n"
" if (bh >= B*H) return;\n"
" const int base=bh*nsplit*(FA_D+2);\n"
" float m_max=-INFINITY;\n"
" for (int s=0; s<nsplit; ++s) {\n"
" m_max=fmax(m_max,partial[base+s*(FA_D+2)+FA_D]);\n"
" }\n"
" float num=0.0f,den=0.0f;\n"
" for (int s=0; s<nsplit; ++s) {\n"
" const float m_s=partial[base+s*(FA_D+2)+FA_D];\n"
" if (m_s == -INFINITY) continue;\n"
" const float w=native_exp(m_s-m_max);\n"
" num += w*partial[base+s*(FA_D+2)+t];\n"
" den += w*partial[base+s*(FA_D+2)+FA_D+1];\n"
" }\n"
" O[bh*FA_D+t]=(half)((den>0.0f) ? num/den : 0.0f);\n"
"}\n"
"// ============================================================================\n"
"// Two-pass GEMM-class PREFILL (S_q large,causal). Reuses the validated\n"
"// variant-C 8x4 image-A/packed-B GEMM for QK^T and P*V with a query-major\n"
"// fp16 score scratch+in-place softmax (no score-matrix transpose). Three\n"
"// stride-aware pre-passes compact the real (strided) Q/K/V into contiguous\n"
"// intermediates so the compute kernels run on dense data. All batch B*H via\n"
"// grid dim 2 (bh). Requires FA_D % 4 == 0; D == FA_D (128 typical).\n"
"// See docs/opencl_backend/flash_attention_optimization.md (Stage 2).\n"
"// ============================================================================\n"
"// pack_q: strided Q[b,h,q,:] -> contiguous Qp[bh][32,Sq,4] (QK B-operand).\n"
"// global=(Sq,FA_D/4,B*H).\n"
"__kernel void tp_pack_q(__global const half* Q,__global half* Qp,\n"
" const int B,const int H,const int Sq,\n"
" const int Qbs,const int Qhs,const int Qss) {\n"
" const int q=get_global_id(0);\n"
" const int g=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" if (q >= Sq || g >= FA_D/4 || bh >= B*H) return;\n"
" const int b=bh/H,h=bh-b*H;\n"
" __global const half* src=Q+(long)b*Qbs+(long)h*Qhs+(long)q*Qss;\n"
" __global half* dst=Qp+(long)bh*(FA_D/4)*Sq*4;\n"
" const int sd=g*4;\n"
" #pragma unroll\n"
" for (int kk=0; kk<4; ++kk) dst[((long)g*Sq+q)*4+kk]=src[sd+kk];\n"
"}\n"
"// trans_k: strided K[b,h,k,:] -> contiguous Kt[bh][FA_D,Skv] (QK A-image).\n"
"// global=(Skv,FA_D,B*H).\n"
"__kernel void tp_trans_k(__global const half* K,__global half* Kt,\n"
" const int B,const int H,const int Skv,\n"
" const int Kbs,const int Khs,const int Kss) {\n"
" const int k=get_global_id(0);\n"
" const int d=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" if (k >= Skv || d >= FA_D || bh >= B*H) return;\n"
" const int b=bh/H,h=bh-b*H;\n"
" Kt[(long)bh*FA_D*Skv+(long)d*Skv+k] =\n"
" K[(long)b*Kbs+(long)h*Khs+(long)k*Kss+d];\n"
"}\n"
"// copy_v: strided V[b,h,k,:] -> contiguous Vc[bh][Skv,FA_D] (PV A-image,natural).\n"
"// global=(Skv,FA_D,B*H).\n"
"__kernel void tp_copy_v(__global const half* V,__global half* Vc,\n"
" const int B,const int H,const int Skv,\n"
" const int Vbs,const int Vhs,const int Vss) {\n"
" const int k=get_global_id(0);\n"
" const int d=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" if (k >= Skv || d >= FA_D || bh >= B*H) return;\n"
" const int b=bh/H,h=bh-b*H;\n"
" Vc[(long)bh*Skv*FA_D+(long)k*FA_D+d] =\n"
" V[(long)b*Vbs+(long)h*Vhs+(long)k*Vss+d];\n"
"}\n"
"// tp_qk_gemm: S[q,k]=scale*(Q[q,:].K[k,:])+causal mask+clamp,query-major.\n"
"// A=Kt image [R=d,M=k=Skv]; B=Qp packed [d/4,q=N=Sq,4]. global=(Skv/8,Sq/4,B*H).\n"
"#ifndef TP_CLAMP\n"
"#define TP_CLAMP 60000.0f\n"
"#endif\n"
"__kernel void tp_qk_gemm(__read_only image1d_buffer_t Kt_img,\n"
" __global const half* Qp,__global half* S,\n"
" const int Sq,const int Skv,const int BH,\n"
" const float scale,const int causal) {\n"
" const int gy=get_global_id(0);\n"
" const int gx=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" const int M=Skv,N=Sq;\n"
" if (gy*8 >= M || gx*4 >= N || bh >= BH) return;\n"
" const int gx_4=gx << 2,gy_8=gy << 3,M_4=M >> 2;\n"
" const int kt_tex_base=bh*FA_D*(M >> 2);\n"
" __global const half* Qph=Qp+(long)bh*(FA_D/4)*N*4;\n"
" __global half* Sh=S+(long)bh*(long)Sq*Skv;\n"
" if (causal && gy_8>(Skv-Sq)+gx_4+3) {\n"
" #define TPINF(NN) { const int q=gx_4+(NN); if (q<N) vstore8((half8)(-INFINITY),0,Sh+(long)q*Skv+gy_8); }\n"
" TPINF(0); TPINF(1); TPINF(2); TPINF(3);\n"
" #undef TPINF\n"
" return;\n"
" }\n"
" float8 c0=(float8)0,c1=(float8)0,c2=(float8)0,c3=(float8)0;\n"
" half8 B0,B1,B2,B3;\n"
" for (int i=0; i<FA_D; i += 4) {\n"
" const int t=kt_tex_base+gy*2+i*M_4;\n"
" B0.s0123=read_imageh(Kt_img,t); B0.s4567=read_imageh(Kt_img,t+1);\n"
" const int t1=kt_tex_base+gy*2+(i+1)*M_4;\n"
" B1.s0123=read_imageh(Kt_img,t1); B1.s4567=read_imageh(Kt_img,t1+1);\n"
" const int t2=kt_tex_base+gy*2+(i+2)*M_4;\n"
" B2.s0123=read_imageh(Kt_img,t2); B2.s4567=read_imageh(Kt_img,t2+1);\n"
" const int t3=kt_tex_base+gy*2+(i+3)*M_4;\n"
" B3.s0123=read_imageh(Kt_img,t3); B3.s4567=read_imageh(Kt_img,t3+1);\n"
" half16 w=vload16(0,Qph+((long)(i >> 2)*N+gx_4)*4);\n"
" const float8 b0=convert_float8(B0),b1=convert_float8(B1),b2=convert_float8(B2),b3=convert_float8(B3);\n"
" c0 += b0*w.s0; c0 += b1*w.s1; c0 += b2*w.s2; c0 += b3*w.s3;\n"
" c1 += b0*w.s4; c1 += b1*w.s5; c1 += b2*w.s6; c1 += b3*w.s7;\n"
" c2 += b0*w.s8; c2 += b1*w.s9; c2 += b2*w.sa; c2 += b3*w.sb;\n"
" c3 += b0*w.sc; c3 += b1*w.sd; c3 += b2*w.se; c3 += b3*w.sf;\n"
" }\n"
" #define TPEMIT(NN, CV) { "" const int q = gx_4 + (NN); "" if (q < N) { "" const int q_pos = (Skv - Sq) + q; "" float8 v = (CV) * scale; half8 hv; "" hv.s0 = (half)((causal && (gy_8+0) > q_pos) ? -INFINITY : clamp(v.s0,-TP_CLAMP,TP_CLAMP)); "" hv.s1 = (half)((causal && (gy_8+1) > q_pos) ? -INFINITY : clamp(v.s1,-TP_CLAMP,TP_CLAMP)); "" hv.s2 = (half)((causal && (gy_8+2) > q_pos) ? -INFINITY : clamp(v.s2,-TP_CLAMP,TP_CLAMP)); "" hv.s3 = (half)((causal && (gy_8+3) > q_pos) ? -INFINITY : clamp(v.s3,-TP_CLAMP,TP_CLAMP)); "" hv.s4 = (half)((causal && (gy_8+4) > q_pos) ? -INFINITY : clamp(v.s4,-TP_CLAMP,TP_CLAMP)); "" hv.s5 = (half)((causal && (gy_8+5) > q_pos) ? -INFINITY : clamp(v.s5,-TP_CLAMP,TP_CLAMP)); "" hv.s6 = (half)((causal && (gy_8+6) > q_pos) ? -INFINITY : clamp(v.s6,-TP_CLAMP,TP_CLAMP)); "" hv.s7 = (half)((causal && (gy_8+7) > q_pos) ? -INFINITY : clamp(v.s7,-TP_CLAMP,TP_CLAMP)); "" vstore8(hv, 0, Sh + (long)q * Skv + gy_8); "" } }\n"
" TPEMIT(0,c0); TPEMIT(1,c1); TPEMIT(2,c2); TPEMIT(3,c3);\n"
" #undef TPEMIT\n"
"}\n"
"// tp_softmax_norm: per (bh,q) row of S,normalize IN PLACE -> P query-major.\n"
"// global=(TP_SM_LW,Sq,B*H),local=(TP_SM_LW,1,1).\n"
"#ifndef TP_SM_LW\n"
"#define TP_SM_LW 64\n"
"#endif\n"
"inline int tp_causal_row(int Sq,int Skv,int q) { return min(Skv-1,(Skv-Sq)+q); }\n"
"__kernel void tp_softmax_norm(__global half* S,const int Sq,const int Skv,const int BH) {\n"
" const int t=get_local_id(0);\n"
" const int q=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" if (q >= Sq || bh >= BH) return;\n"
" __global half* Sh=S+(long)bh*Sq*Skv+(long)q*Skv;\n"
" __local float redm[TP_SM_LW];\n"
" __local float redl[TP_SM_LW];\n"
" const int kcap=tp_causal_row(Sq,Skv,q);\n"
" // pass 1: ONLINE (m,l) in one causal scan (running-max rescale) -> 2 total\n"
" // S-touches instead of 3 (max-pass+sum-pass fused).\n"
" float m=-INFINITY,l=0.0f;\n"
" for (int k=t; k <= kcap; k += TP_SM_LW) {\n"
" float s=(float)Sh[k];\n"
" if (!isinf(s)) { float mn=fmax(m,s); l=l*native_exp(m-mn)+native_exp(s-mn); m=mn; }\n"
" }\n"
" redm[t]=m; redl[t]=l; barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int o=TP_SM_LW >> 1; o>0; o >>= 1) {\n"
" if (t<o) {\n"
" float ma=redm[t],mb=redm[t+o],la=redl[t],lb=redl[t+o];\n"
" float mn=fmax(ma,mb);\n"
" redl[t]=(isinf(mn) ? 0.0f : la*native_exp(ma-mn)+lb*native_exp(mb-mn));\n"
" redm[t]=mn;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" m=redm[0]; l=redl[0];\n"
" const float inv=(l>0.0f) ? (1.0f/l) : 0.0f;\n"
" // pass 2: write P in place,only up to pv_gemm's per-n-tile read bound (wcap);\n"
" // masked keys in (q_pos,wcap) -> 0; keys >= wcap are never read by pv.\n"
" const int gx4=q & ~3;\n"
" const int wcap=min(Skv,(((Skv-Sq)+gx4+3)+4) & ~3);\n"
" for (int k=t; k<wcap; k += TP_SM_LW) {\n"
" float s=(float)Sh[k];\n"
" Sh[k]=(half)((isinf(m) || isinf(s)) ? 0.0f : native_exp(s-m)*inv);\n"
" }\n"
"}\n"
"// tp_pv_gemm: O[q,d]=sum_k P[q,k] V[k,d]. A=Vc image [R=k,M=d=FA_D];\n"
"// B=P query-major (in place in S) read direct via 4x vload4. causal reduction\n"
"// bound per n-tile. global=(FA_D/8,Sq/4,B*H). O contiguous [B*H,Sq,FA_D].\n"
"__kernel void tp_pv_gemm(__read_only image1d_buffer_t V_img,\n"
" __global const half* P,__global half* O,\n"
" const int Sq,const int Skv,const int BH,const int causal) {\n"
" const int gy=get_global_id(0);\n"
" const int gx=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" const int M=FA_D,N=Sq;\n"
" if (gy*8 >= M || gx*4 >= N || bh >= BH) return;\n"
" const int gx_4=gx << 2,gy_8=gy << 3,M_4=M >> 2;\n"
" int kmax=Skv;\n"
" if (causal) { const int qpm=(Skv-Sq)+gx_4+3; kmax=min(Skv,(qpm+4) & ~3); }\n"
" const int v_tex_base=bh*Skv*(FA_D >> 2);\n"
" __global const half* Ph=P+(long)bh*(long)Sq*Skv;\n"
" __global half* Oh=O+(long)bh*(long)Sq*FA_D;\n"
" __global const half* p0r=Ph+(long)(gx_4+0)*Skv;\n"
" __global const half* p1r=Ph+(long)(gx_4+1)*Skv;\n"
" __global const half* p2r=Ph+(long)(gx_4+2)*Skv;\n"
" __global const half* p3r=Ph+(long)(gx_4+3)*Skv;\n"
" float8 c0=(float8)0,c1=(float8)0,c2=(float8)0,c3=(float8)0;\n"
" half8 B0,B1,B2,B3;\n"
" for (int i=0; i<kmax; i += 4) {\n"
" const int t=v_tex_base+gy*2+i*M_4;\n"
" B0.s0123=read_imageh(V_img,t); B0.s4567=read_imageh(V_img,t+1);\n"
" const int t1=v_tex_base+gy*2+(i+1)*M_4;\n"
" B1.s0123=read_imageh(V_img,t1); B1.s4567=read_imageh(V_img,t1+1);\n"
" const int t2=v_tex_base+gy*2+(i+2)*M_4;\n"
" B2.s0123=read_imageh(V_img,t2); B2.s4567=read_imageh(V_img,t2+1);\n"
" const int t3=v_tex_base+gy*2+(i+3)*M_4;\n"
" B3.s0123=read_imageh(V_img,t3); B3.s4567=read_imageh(V_img,t3+1);\n"
" half4 p0=vload4(0,p0r+i),p1=vload4(0,p1r+i),p2=vload4(0,p2r+i),p3=vload4(0,p3r+i);\n"
" const float8 b0=convert_float8(B0),b1=convert_float8(B1),b2=convert_float8(B2),b3=convert_float8(B3);\n"
" c0 += b0*p0.s0; c0 += b1*p0.s1; c0 += b2*p0.s2; c0 += b3*p0.s3;\n"
" c1 += b0*p1.s0; c1 += b1*p1.s1; c1 += b2*p1.s2; c1 += b3*p1.s3;\n"
" c2 += b0*p2.s0; c2 += b1*p2.s1; c2 += b2*p2.s2; c2 += b3*p2.s3;\n"
" c3 += b0*p3.s0; c3 += b1*p3.s1; c3 += b2*p3.s2; c3 += b3*p3.s3;\n"
" }\n"
" #define TPEMITO(NN,CV) { const int q=gx_4+(NN); if (q<N) vstore8(convert_half8(CV),0,Oh+(long)q*FA_D+gy_8); }\n"
" TPEMITO(0,c0); TPEMITO(1,c1); TPEMITO(2,c2); TPEMITO(3,c3);\n"
" #undef TPEMITO\n"
"}\n"
;
} // namespace mllm::opencl
