#include "a_opencl_source_map.hpp" 
namespace mllm::opencl { 
const char* flash_attention = 
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"// FlashAttention v1 (Dao et al.,2022),forward pass for inference.\n"
"// Same paper algorithm (K/V tiled in __local,online softmax merge with running\n"
"// (m_i,l_i,O_i) per Q row),but with a redesigned thread mapping for OpenCL:\n"
"//\n"
"// local_size=FA_D (= head_dim,e.g. 128 for Qwen3)\n"
"// threads 0..(FA_BR*FA_BC-1) → compute S[i][c]=Q_i . K_c serially\n"
"// (one thread per S element,NO tree reduce)\n"
"// threads 0..(FA_D-1) → compute pv=sum_c P[i][c]*V_local[c][d]\n"
"// (one thread per d-position; serial loop in c)\n"
"//\n"
"// This kills the per-S-element tree reduction barriers that dominated the\n"
"// previous implementation: ~3 barriers per j-iter total (load/S/end-of-j)\n"
"// instead of ~580.\n"
"//\n"
"// Layout: BHSD (all input tensors may be non-contiguous; strides passed in).\n"
"// Output O is contiguous BHSD.\n"
"#ifndef FA_BR\n"
"#define FA_BR 4\n"
"#endif\n"
"#ifndef FA_BC\n"
"#define FA_BC 16\n"
"#endif\n"
"#ifndef FA_D\n"
"#define FA_D 128\n"
"#endif\n"
"#define FA_S_THREADS (FA_BR*FA_BC) //=64 active threads during S compute\n"
"// ---------------------------------------------------------------- fp32\n"
"__kernel void flash_attention_fp32(\n"
" __global const float *Q,__global const float *K,__global const float *V,\n"
" __global float *O,\n"
" const int B,const int H,const int S_q,const int S_kv,const int D,\n"
" const int Q_b_stride,const int Q_h_stride,const int Q_s_stride,\n"
" const int K_b_stride,const int K_h_stride,const int K_s_stride,\n"
" const int V_b_stride,const int V_h_stride,const int V_s_stride,\n"
" const float scale,const int causal_mask) {\n"
" const int t=get_local_id(0); // 0..FA_D-1\n"
" const int q_block=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" if (bh >= B*H) return;\n"
" const int q_row_start=q_block*FA_BR;\n"
" if (q_row_start >= S_q) return;\n"
" const int b=bh/H;\n"
" const int h=bh-b*H;\n"
" const int q_h_off=b*Q_b_stride+h*Q_h_stride;\n"
" const int k_h_off=b*K_b_stride+h*K_h_stride;\n"
" const int v_h_off=b*V_b_stride+h*V_h_stride;\n"
" const int o_h_off=bh*S_q*D;\n"
" __local float Q_local[FA_BR*FA_D];\n"
" __local float K_local[FA_BC*FA_D];\n"
" __local float V_local[FA_BC*FA_D];\n"
" __local float S_local[FA_BR*FA_BC];\n"
" __local float m_il[FA_BR];\n"
" __local float l_il[FA_BR];\n"
" // Load Q tile (B_r × D) — each thread (= d-position) loads B_r elements.\n"
" for (int i=0; i<FA_BR; ++i) {\n"
" const int q_row=q_row_start+i;\n"
" Q_local[i*FA_D+t] =\n"
" (q_row<S_q) ? Q[q_h_off+q_row*Q_s_stride+t] : 0.0f;\n"
" }\n"
" // Init per-Q-row running stats (only first FA_BR threads write).\n"
" if (t<FA_BR) {\n"
" m_il[t]=-INFINITY;\n"
" l_il[t]=0.0f;\n"
" }\n"
" // O accumulator in private registers: one float per Q row at this thread's d.\n"
" float o_priv[FA_BR];\n"
" for (int i=0; i<FA_BR; ++i) o_priv[i]=0.0f;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // Outer loop over K/V blocks (paper Algorithm 1,line 5).\n"
" for (int j_start=0; j_start<S_kv; j_start += FA_BC) {\n"
" // Load K_j,V_j tiles cooperatively (each thread loads B_c elements).\n"
" for (int c=0; c<FA_BC; ++c) {\n"
" const int k_row=j_start+c;\n"
" if (k_row<S_kv) {\n"
" K_local[c*FA_D+t]=K[k_h_off+k_row*K_s_stride+t];\n"
" V_local[c*FA_D+t]=V[v_h_off+k_row*V_s_stride+t];\n"
" } else {\n"
" K_local[c*FA_D+t]=0.0f;\n"
" V_local[c*FA_D+t]=0.0f;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // S_ij=Q_i K_j^T. Each S element computed by ONE thread doing a serial\n"
" // 128-element dot product in registers. NO tree reduction,NO per-element\n"
" // barriers. Threads with t >= FA_S_THREADS idle this phase.\n"
" if (t<FA_S_THREADS) {\n"
" const int i=t/FA_BC;\n"
" const int c=t-i*FA_BC;\n"
" float acc=0.0f;\n"
" for (int d=0; d<FA_D; ++d) {\n"
" acc += Q_local[i*FA_D+d]*K_local[c*FA_D+d];\n"
" }\n"
" const int q_row=q_row_start+i;\n"
" const int k_row=j_start+c;\n"
" const int q_pos=S_kv-S_q+q_row;\n"
" if (q_row >= S_q || k_row >= S_kv ||\n"
" (causal_mask && k_row>q_pos)) {\n"
" acc=-INFINITY;\n"
" } else {\n"
" acc *= scale;\n"
" }\n"
" S_local[i*FA_BC+c]=acc;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // Online softmax merge per Q row. All threads compute the same scalars\n"
" // (m_tilde,l_tilde,m_new,...); pv is the only per-d quantity.\n"
" for (int i=0; i<FA_BR; ++i) {\n"
" float m_tilde=-INFINITY;\n"
" for (int c=0; c<FA_BC; ++c) {\n"
" m_tilde=fmax(m_tilde,S_local[i*FA_BC+c]);\n"
" }\n"
" float l_tilde=0.0f;\n"
" float pv=0.0f;\n"
" for (int c=0; c<FA_BC; ++c) {\n"
" const float s=S_local[i*FA_BC+c];\n"
" const float p=(s == -INFINITY) ? 0.0f : exp(s-m_tilde);\n"
" l_tilde += p;\n"
" pv += p*V_local[c*FA_D+t];\n"
" }\n"
" const float m_old=m_il[i];\n"
" const float l_old=l_il[i];\n"
" const float m_new=fmax(m_old,m_tilde);\n"
" const float a=(m_old == -INFINITY) ? 0.0f : exp(m_old-m_new);\n"
" const float bb=(m_tilde == -INFINITY) ? 0.0f : exp(m_tilde-m_new);\n"
" const float l_new=a*l_old+bb*l_tilde;\n"
" o_priv[i] =\n"
" (l_new>0.0f) ? (l_old*a*o_priv[i]+bb*pv)/l_new : 0.0f;\n"
" if (t == 0) {\n"
" m_il[i]=m_new;\n"
" l_il[i]=l_new;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" // Write O (one float per (q_row,d) for this thread).\n"
" for (int i=0; i<FA_BR; ++i) {\n"
" const int q_row=q_row_start+i;\n"
" if (q_row<S_q) { O[o_h_off+q_row*D+t]=o_priv[i]; }\n"
" }\n"
"}\n"
"// ---------------------------------------------------------------- fp16 (optimized)\n"
"//\n"
"// Optimized vs the fp32 reference above,applying lessons from the tuned OpenCL\n"
"// GEMM/GEMV kernels. The fp32 kernel is left untouched as the numeric reference.\n"
"//\n"
"// FA_BR_H q-rows per workgroup (default 8 — the host must launch q_blocks =\n"
"// ceil(S_q/FA_BR_H) for fp16); FA_BC_H=FA_D/4 keys per K/V tile. With\n"
"// FA_BR_H=8,D=128 → FA_BC_H=32 and FA_BR_H*FA_BC_H=256=2*FA_D,so each\n"
"// of the 128 lanes computes TWO S elements in QK^T (two Q rows i0 and i0+4\n"
"// sharing column c → the K[c] row is loaded once and reused → cross-q reuse,\n"
"// and the per-j-iter load+barrier overhead is amortized over 2x the rows).\n"
"//\n"
"// Other techniques: native-half LDS storage; transposed-V LDS tile for\n"
"// contiguous vectorized P·V; hoisted producer-lane softmax (native_exp);\n"
"// half8-vectorized QK^T dot; causal block-skip of fully-masked K/V blocks.\n"
"//\n"
"// PRECISION INVARIANT: storage+multiply operands are half; ALL accumulators\n"
"// (QK^T dot,P·V sum,o_priv across the whole S_kv loop) and softmax stats\n"
"// (m,l,a,bb,l_new) stay fp32 — they feed exp(). Requires FA_D % 4 == 0 and\n"
"// FA_BR_H*FA_BC_H == 2*FA_D (true for FA_BR_H=8,any D divisible by 4).\n"
"#ifndef FA_BR_H\n"
"#define FA_BR_H 8\n"
"#endif\n"
"#define FA_BC_H (FA_D/4) // 32 for D=128\n"
"#define FA_ROWSTEP (FA_D/FA_BC_H) // 4: rows handled by a lane are i0+s*ROWSTEP\n"
"#define FA_NSPL (FA_BR_H*FA_BC_H/FA_D) // S elements per lane (2 for BR=8,4 for BR=16)\n"
"__kernel void flash_attention_fp16(\n"
" __global const half *Q,__global const half *K,__global const half *V,\n"
" __global half *O,\n"
" const int B,const int H,const int S_q,const int S_kv,const int D,\n"
" const int Q_b_stride,const int Q_h_stride,const int Q_s_stride,\n"
" const int K_b_stride,const int K_h_stride,const int K_s_stride,\n"
" const int V_b_stride,const int V_h_stride,const int V_s_stride,\n"
" const float scale,const int causal_mask) {\n"
" const int t=get_local_id(0); // 0..FA_D-1\n"
" const int q_block=get_global_id(1);\n"
" const int bh=get_global_id(2);\n"
" if (bh >= B*H) return;\n"
" const int q_row_start=q_block*FA_BR_H;\n"
" if (q_row_start >= S_q) return;\n"
" // Valid rows in this workgroup (< FA_BR_H only for the last block/decode).\n"
" // A uniform loop bound (not a per-iter `continue`) keeps the compiler's loop\n"
" // optimization for full blocks while letting decode (S_q=1) skip the waste.\n"
" const int nrows=min(FA_BR_H,S_q-q_row_start);\n"
" const int b=bh/H;\n"
" const int h=bh-b*H;\n"
" const int q_h_off=b*Q_b_stride+h*Q_h_stride;\n"
" const int k_h_off=b*K_b_stride+h*K_h_stride;\n"
" const int v_h_off=b*V_b_stride+h*V_h_stride;\n"
" const int o_h_off=bh*S_q*D;\n"
" __local half Q_local[FA_BR_H*FA_D];\n"
" __local half K_local[FA_BC_H*FA_D]; // c-major [c*D+d] for the QK^T dot\n"
" __local half V_localT[FA_D*FA_BC_H]; // TRANSPOSED [d*FA_BC_H+c] for P·V\n"
" __local float S_local[FA_BR_H*FA_BC_H]; // scores (fp32)\n"
" __local float m_il[FA_BR_H];\n"
" __local float l_il[FA_BR_H];\n"
" __local float sh_a[FA_BR_H];\n"
" __local float sh_bb[FA_BR_H];\n"
" __local float sh_lold[FA_BR_H];\n"
" __local float sh_lnew[FA_BR_H];\n"
" for (int i=0; i<FA_BR_H; ++i) {\n"
" const int q_row=q_row_start+i;\n"
" Q_local[i*FA_D+t] =\n"
" (q_row<S_q) ? Q[q_h_off+q_row*Q_s_stride+t] : (half)0;\n"
" }\n"
" if (t<FA_BR_H) {\n"
" m_il[t]=-INFINITY;\n"
" l_il[t]=0.0f;\n"
" }\n"
" float o_priv[FA_BR_H];\n"
" for (int i=0; i<FA_BR_H; ++i) o_priv[i]=0.0f;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // Causal block-skip: cap the j-loop at this q_block's last diagonal block.\n"
" int j_max=S_kv;\n"
" if (causal_mask) {\n"
" const int last_q_pos=S_kv-S_q+(q_row_start+FA_BR_H-1);\n"
" j_max=min(S_kv,last_q_pos+1);\n"
" }\n"
" for (int j_start=0; j_start<j_max; j_start += FA_BC_H) {\n"
" for (int c=0; c<FA_BC_H; ++c) {\n"
" const int k_row=j_start+c;\n"
" if (k_row<S_kv) {\n"
" K_local[c*FA_D+t]=K[k_h_off+k_row*K_s_stride+t];\n"
" V_localT[t*FA_BC_H+c]=V[v_h_off+k_row*V_s_stride+t];\n"
" } else {\n"
" K_local[c*FA_D+t]=(half)0;\n"
" V_localT[t*FA_BC_H+c]=(half)0;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // QK^T — each of the 128 lanes computes TWO S elements: rows i0 and\n"
" // i0+FA_ROWSTEP at the same column c,sharing the K[c] row load. Invalid\n"
" // (masked/out-of-range) rows are gated out so partial blocks (e.g. decode\n"
" // S_q=1 under FA_BR_H=8) don't pay for the wasted rows.\n"
" {\n"
" const int c=t % FA_BC_H;\n"
" const int i0=t/FA_BC_H;\n"
" const int k_row=j_start+c;\n"
" __local const half* krow=K_local+c*FA_D;\n"
" float8 acc[FA_NSPL];\n"
" #pragma unroll\n"
" for (int s=0; s<FA_NSPL; ++s) acc[s]=(float8)(0.0f);\n"
" for (int d8=0; d8<FA_D/8; ++d8) {\n"
" float8 kf=convert_float8(vload8(d8,krow)); // shared K row across rows\n"
" #pragma unroll\n"
" for (int s=0; s<FA_NSPL; ++s) {\n"
" acc[s] += convert_float8(vload8(d8,Q_local+(i0+s*FA_ROWSTEP)*FA_D))*kf;\n"
" }\n"
" }\n"
" #pragma unroll\n"
" for (int s=0; s<FA_NSPL; ++s) {\n"
" const int i=i0+s*FA_ROWSTEP;\n"
" const int qr=q_row_start+i;\n"
" const int qp=S_kv-S_q+qr;\n"
" const float8 a=acc[s];\n"
" const float v=a.s0+a.s1+a.s2+a.s3+a.s4+a.s5+a.s6+a.s7;\n"
" S_local[i*FA_BC_H+c] =\n"
" (qr >= S_q || k_row >= S_kv || (causal_mask && k_row>qp)) ? -INFINITY : v*scale;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // Online softmax — hoisted: one producer lane per valid Q row.\n"
" if (t<nrows) {\n"
" const int i=t;\n"
" float m_tilde=-INFINITY;\n"
" for (int c=0; c<FA_BC_H; ++c) {\n"
" m_tilde=fmax(m_tilde,S_local[i*FA_BC_H+c]);\n"
" }\n"
" float l_tilde=0.0f;\n"
" for (int c=0; c<FA_BC_H; ++c) {\n"
" const float s=S_local[i*FA_BC_H+c];\n"
" const float p=(s == -INFINITY) ? 0.0f : native_exp(s-m_tilde);\n"
" S_local[i*FA_BC_H+c]=p; // alias: overwrite score with prob (max already taken)\n"
" l_tilde += p;\n"
" }\n"
" const float m_old=m_il[i];\n"
" const float l_old=l_il[i];\n"
" const float m_new=fmax(m_old,m_tilde);\n"
" const float a=(m_old == -INFINITY) ? 0.0f : native_exp(m_old-m_new);\n"
" const float bb=(m_tilde == -INFINITY) ? 0.0f : native_exp(m_tilde-m_new);\n"
" const float l_new=a*l_old+bb*l_tilde;\n"
" sh_a[i]=a;\n"
" sh_bb[i]=bb;\n"
" sh_lold[i]=l_old;\n"
" sh_lnew[i]=l_new;\n"
" m_il[i]=m_new;\n"
" l_il[i]=l_new;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" // P·V+O rescale — ALL lanes: lane t owns d=t; FA_BR_H rows,vectorized in c.\n"
" {\n"
" __local const half* vrow=V_localT+t*FA_BC_H;\n"
" for (int i=0; i<nrows; ++i) {\n"
" __local const float* prow=S_local+i*FA_BC_H;\n"
" float8 pv8=(float8)(0.0f);\n"
" for (int c8=0; c8<FA_BC_H/8; ++c8) {\n"
" pv8 += vload8(c8,prow)*convert_float8(vload8(c8,vrow));\n"
" }\n"
" const float pv=pv8.s0+pv8.s1+pv8.s2+pv8.s3 +\n"
" pv8.s4+pv8.s5+pv8.s6+pv8.s7;\n"
" const float a=sh_a[i],bb=sh_bb[i];\n"
" const float l_old=sh_lold[i],l_new=sh_lnew[i];\n"
" o_priv[i] =\n"
" (l_new>0.0f) ? (l_old*a*o_priv[i]+bb*pv)/l_new : 0.0f;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" for (int i=0; i<nrows; ++i) {\n"
" O[o_h_off+(q_row_start+i)*D+t]=(half)o_priv[i];\n"
" }\n"
"}\n"
;
} // namespace mllm::opencl
