#include "a_opencl_source_map.hpp"
namespace mllm::opencl {
const char* flash_attention = "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
                              "// FlashAttention v1 (Dao et al.,2022),forward pass for inference.\n"
                              "// Faithful to Algorithm 1 in the paper:\n"
                              "//-K/V tiles loaded into SRAM (__local) once per outer j iteration and\n"
                              "// reused across all B_r Q rows in this work-group.\n"
                              "//-Online softmax merge with running (m_i,l_i,O_i) per Q row.\n"
                              "//\n"
                              "// Layout: BHSD,all input tensors may be non-contiguous (strides passed in).\n"
                              "// Q: [B,H,S_q,D]\n"
                              "// K: [B,H,S_kv,D] (already GQA-expanded to H=q_heads)\n"
                              "// V: [B,H,S_kv,D]\n"
                              "// O: [B,H,S_q,D] (always contiguous,allocated by reshape())\n"
                              "//\n"
                              "// Parallelization: one work-group per (batch,head,q_block),where each\n"
                              "// q_block covers B_r Q rows. local_size MUST equal FA_D (head dim,must be\n"
                              "// power-of-two for the tree reduction). Each thread=one d-position.\n"
                              "#ifndef FA_BR\n"
                              "#define FA_BR 4 // Q rows per work-group\n"
                              "#endif\n"
                              "#ifndef FA_BC\n"
                              "#define FA_BC 16 // K/V cols per inner tile\n"
                              "#endif\n"
                              "#ifndef FA_D\n"
                              "#define FA_D 128 // head dim; pass via -DFA_D=… at build time\n"
                              "#endif\n"
                              "// ---------------------------------------------------------------- fp32\n"
                              "__kernel void flash_attention_fp32(\n"
                              " __global const float *Q,__global const float *K,__global const float *V,\n"
                              " __global float *O,\n"
                              " const int B,const int H,const int S_q,const int S_kv,const int D,\n"
                              " const int Q_b_stride,const int Q_h_stride,const int Q_s_stride,\n"
                              " const int K_b_stride,const int K_h_stride,const int K_s_stride,\n"
                              " const int V_b_stride,const int V_h_stride,const int V_s_stride,\n"
                              " const float scale,const int causal_mask) {\n"
                              " const int d=get_local_id(0);\n"
                              " const int q_block=get_global_id(1);\n"
                              " const int bh=get_global_id(2);\n"
                              " if (bh >= B*H) return;\n"
                              " const int q_row_start=q_block*FA_BR;\n"
                              " if (q_row_start >= S_q) return;\n"
                              " const int local_size=get_local_size(0);\n"
                              " const int b=bh/H;\n"
                              " const int h=bh-b*H;\n"
                              " const int q_h_off=b*Q_b_stride+h*Q_h_stride;\n"
                              " const int k_h_off=b*K_b_stride+h*K_h_stride;\n"
                              " const int v_h_off=b*V_b_stride+h*V_h_stride;\n"
                              " const int o_h_off=bh*S_q*D;\n"
                              " __local float Q_local[FA_BR*FA_D];\n"
                              " __local float K_local[FA_BC*FA_D];\n"
                              " __local float V_local[FA_BC*FA_D];\n"
                              " __local float S_local[FA_BR*FA_BC];\n"
                              " __local float reduce_buf[FA_D];\n"
                              " __local float m_il[FA_BR];\n"
                              " __local float l_il[FA_BR];\n"
                              " // Load Q tile for this q_block (B_r × D),zero-pad rows past S_q.\n"
                              " for (int i=0; i<FA_BR; ++i) {\n"
                              " const int q_row=q_row_start+i;\n"
                              " Q_local[i*FA_D+d] =\n"
                              " (q_row<S_q) ? Q[q_h_off+q_row*Q_s_stride+d] : 0.0f;\n"
                              " }\n"
                              " // Init running stats per i (only first FA_BR threads write).\n"
                              " if (d<FA_BR) {\n"
                              " m_il[d]=-INFINITY;\n"
                              " l_il[d]=0.0f;\n"
                              " }\n"
                              " // O accumulator in registers,one per Q row,this thread's d-position.\n"
                              " float o_priv[FA_BR];\n"
                              " for (int i=0; i<FA_BR; ++i) o_priv[i]=0.0f;\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " // Outer loop over K/V blocks (paper Algorithm 1,line 5).\n"
                              " for (int j_start=0; j_start<S_kv; j_start += FA_BC) {\n"
                              " // Load K_j and V_j tiles cooperatively.\n"
                              " for (int c=0; c<FA_BC; ++c) {\n"
                              " const int k_row=j_start+c;\n"
                              " if (k_row<S_kv) {\n"
                              " K_local[c*FA_D+d]=K[k_h_off+k_row*K_s_stride+d];\n"
                              " V_local[c*FA_D+d]=V[v_h_off+k_row*V_s_stride+d];\n"
                              " } else {\n"
                              " K_local[c*FA_D+d]=0.0f;\n"
                              " V_local[c*FA_D+d]=0.0f;\n"
                              " }\n"
                              " }\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " // S_ij=Q_i K_j^T (B_r × B_c),one tree-reduction per element.\n"
                              " for (int i=0; i<FA_BR; ++i) {\n"
                              " for (int c=0; c<FA_BC; ++c) {\n"
                              " reduce_buf[d]=Q_local[i*FA_D+d]*K_local[c*FA_D+d];\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " for (int off=local_size/2; off>0; off >>= 1) {\n"
                              " if (d<off) reduce_buf[d] += reduce_buf[d+off];\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " }\n"
                              " if (d == 0) {\n"
                              " float s=reduce_buf[0]*scale;\n"
                              " const int q_row=q_row_start+i;\n"
                              " const int k_row=j_start+c;\n"
                              " const int q_pos=S_kv-S_q+q_row;\n"
                              " if (q_row >= S_q || k_row >= S_kv ||\n"
                              " (causal_mask && k_row>q_pos)) {\n"
                              " s=-INFINITY;\n"
                              " }\n"
                              " S_local[i*FA_BC+c]=s;\n"
                              " }\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " }\n"
                              " }\n"
                              " // Online softmax merge per Q row. All threads compute the same scalars\n"
                              " // from S_local; PV is the only per-d quantity.\n"
                              " for (int i=0; i<FA_BR; ++i) {\n"
                              " float m_tilde=-INFINITY;\n"
                              " for (int c=0; c<FA_BC; ++c) {\n"
                              " m_tilde=fmax(m_tilde,S_local[i*FA_BC+c]);\n"
                              " }\n"
                              " float l_tilde=0.0f;\n"
                              " float pv=0.0f;\n"
                              " for (int c=0; c<FA_BC; ++c) {\n"
                              " const float s=S_local[i*FA_BC+c];\n"
                              " const float p=(s == -INFINITY) ? 0.0f : exp(s-m_tilde);\n"
                              " l_tilde += p;\n"
                              " pv += p*V_local[c*FA_D+d];\n"
                              " }\n"
                              " const float m_old=m_il[i];\n"
                              " const float l_old=l_il[i];\n"
                              " const float m_new=fmax(m_old,m_tilde);\n"
                              " const float a=(m_old == -INFINITY) ? 0.0f : exp(m_old-m_new);\n"
                              " const float bb=(m_tilde == -INFINITY) ? 0.0f : exp(m_tilde-m_new);\n"
                              " const float l_new=a*l_old+bb*l_tilde;\n"
                              " o_priv[i] =\n"
                              " (l_new>0.0f) ? (l_old*a*o_priv[i]+bb*pv)/l_new : 0.0f;\n"
                              " if (d == 0) {\n"
                              " m_il[i]=m_new;\n"
                              " l_il[i]=l_new;\n"
                              " }\n"
                              " }\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " }\n"
                              " // Write O.\n"
                              " for (int i=0; i<FA_BR; ++i) {\n"
                              " const int q_row=q_row_start+i;\n"
                              " if (q_row<S_q) { O[o_h_off+q_row*D+d]=o_priv[i]; }\n"
                              " }\n"
                              "}\n"
                              "// ---------------------------------------------------------------- fp16\n"
                              "__kernel void flash_attention_fp16(\n"
                              " __global const half *Q,__global const half *K,__global const half *V,\n"
                              " __global half *O,\n"
                              " const int B,const int H,const int S_q,const int S_kv,const int D,\n"
                              " const int Q_b_stride,const int Q_h_stride,const int Q_s_stride,\n"
                              " const int K_b_stride,const int K_h_stride,const int K_s_stride,\n"
                              " const int V_b_stride,const int V_h_stride,const int V_s_stride,\n"
                              " const float scale,const int causal_mask) {\n"
                              " const int d=get_local_id(0);\n"
                              " const int q_block=get_global_id(1);\n"
                              " const int bh=get_global_id(2);\n"
                              " if (bh >= B*H) return;\n"
                              " const int q_row_start=q_block*FA_BR;\n"
                              " if (q_row_start >= S_q) return;\n"
                              " const int local_size=get_local_size(0);\n"
                              " const int b=bh/H;\n"
                              " const int h=bh-b*H;\n"
                              " const int q_h_off=b*Q_b_stride+h*Q_h_stride;\n"
                              " const int k_h_off=b*K_b_stride+h*K_h_stride;\n"
                              " const int v_h_off=b*V_b_stride+h*V_h_stride;\n"
                              " const int o_h_off=bh*S_q*D;\n"
                              " __local float Q_local[FA_BR*FA_D];\n"
                              " __local float K_local[FA_BC*FA_D];\n"
                              " __local float V_local[FA_BC*FA_D];\n"
                              " __local float S_local[FA_BR*FA_BC];\n"
                              " __local float reduce_buf[FA_D];\n"
                              " __local float m_il[FA_BR];\n"
                              " __local float l_il[FA_BR];\n"
                              " for (int i=0; i<FA_BR; ++i) {\n"
                              " const int q_row=q_row_start+i;\n"
                              " Q_local[i*FA_D+d] =\n"
                              " (q_row<S_q) ? (float)Q[q_h_off+q_row*Q_s_stride+d] : 0.0f;\n"
                              " }\n"
                              " if (d<FA_BR) {\n"
                              " m_il[d]=-INFINITY;\n"
                              " l_il[d]=0.0f;\n"
                              " }\n"
                              " float o_priv[FA_BR];\n"
                              " for (int i=0; i<FA_BR; ++i) o_priv[i]=0.0f;\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " for (int j_start=0; j_start<S_kv; j_start += FA_BC) {\n"
                              " for (int c=0; c<FA_BC; ++c) {\n"
                              " const int k_row=j_start+c;\n"
                              " if (k_row<S_kv) {\n"
                              " K_local[c*FA_D+d]=(float)K[k_h_off+k_row*K_s_stride+d];\n"
                              " V_local[c*FA_D+d]=(float)V[v_h_off+k_row*V_s_stride+d];\n"
                              " } else {\n"
                              " K_local[c*FA_D+d]=0.0f;\n"
                              " V_local[c*FA_D+d]=0.0f;\n"
                              " }\n"
                              " }\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " for (int i=0; i<FA_BR; ++i) {\n"
                              " for (int c=0; c<FA_BC; ++c) {\n"
                              " reduce_buf[d]=Q_local[i*FA_D+d]*K_local[c*FA_D+d];\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " for (int off=local_size/2; off>0; off >>= 1) {\n"
                              " if (d<off) reduce_buf[d] += reduce_buf[d+off];\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " }\n"
                              " if (d == 0) {\n"
                              " float s=reduce_buf[0]*scale;\n"
                              " const int q_row=q_row_start+i;\n"
                              " const int k_row=j_start+c;\n"
                              " const int q_pos=S_kv-S_q+q_row;\n"
                              " if (q_row >= S_q || k_row >= S_kv ||\n"
                              " (causal_mask && k_row>q_pos)) {\n"
                              " s=-INFINITY;\n"
                              " }\n"
                              " S_local[i*FA_BC+c]=s;\n"
                              " }\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " }\n"
                              " }\n"
                              " for (int i=0; i<FA_BR; ++i) {\n"
                              " float m_tilde=-INFINITY;\n"
                              " for (int c=0; c<FA_BC; ++c) {\n"
                              " m_tilde=fmax(m_tilde,S_local[i*FA_BC+c]);\n"
                              " }\n"
                              " float l_tilde=0.0f;\n"
                              " float pv=0.0f;\n"
                              " for (int c=0; c<FA_BC; ++c) {\n"
                              " const float s=S_local[i*FA_BC+c];\n"
                              " const float p=(s == -INFINITY) ? 0.0f : exp(s-m_tilde);\n"
                              " l_tilde += p;\n"
                              " pv += p*V_local[c*FA_D+d];\n"
                              " }\n"
                              " const float m_old=m_il[i];\n"
                              " const float l_old=l_il[i];\n"
                              " const float m_new=fmax(m_old,m_tilde);\n"
                              " const float a=(m_old == -INFINITY) ? 0.0f : exp(m_old-m_new);\n"
                              " const float bb=(m_tilde == -INFINITY) ? 0.0f : exp(m_tilde-m_new);\n"
                              " const float l_new=a*l_old+bb*l_tilde;\n"
                              " o_priv[i] =\n"
                              " (l_new>0.0f) ? (l_old*a*o_priv[i]+bb*pv)/l_new : 0.0f;\n"
                              " if (d == 0) {\n"
                              " m_il[i]=m_new;\n"
                              " l_il[i]=l_new;\n"
                              " }\n"
                              " }\n"
                              " barrier(CLK_LOCAL_MEM_FENCE);\n"
                              " }\n"
                              " for (int i=0; i<FA_BR; ++i) {\n"
                              " const int q_row=q_row_start+i;\n"
                              " if (q_row<S_q) { O[o_h_off+q_row*D+d]=(half)o_priv[i]; }\n"
                              " }\n"
                              "}\n";
}  // namespace mllm::opencl
