#include "a_opencl_source_map.hpp"
namespace mllm::opencl {
const char* rmsnorm = "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
                      "#define RMSNORM_WG_SIZE 256\n"
                      "typedef struct {\n"
                      " half d;\n"
                      " uchar qs[16];\n"
                      "} block_q4_0;\n"
                      "inline float dequantize_q4_0(const __global block_q4_0 *blocks,int index) {\n"
                      " const int block_idx=index/32;\n"
                      " const int quant_idx_in_block=index % 32;\n"
                      " const __global block_q4_0 *b=&blocks[block_idx];\n"
                      " const uchar quant_pair=b->qs[quant_idx_in_block/2];\n"
                      " const int nibble=(quant_idx_in_block % 2==0)?(quant_pair&0x0F):(quant_pair>>4);\n"
                      " return (float)b->d*(float)(nibble-8);\n"
                      "}\n"
                      "__kernel void rmsnorm_f32_q4(\n"
                      " __global const void *src_void,\n"
                      " __global void *dst_void,\n"
                      " __global const void *weights,\n"
                      " const int weight_is_q4,\n"
                      " const int D,\n"
                      " const float epsilon,\n"
                      " const int add_unit_offset,\n"
                      " const ulong src_offset_bytes,\n"
                      " const ulong dst_offset_bytes\n"
                      ") {\n"
                      " __global const float *src=(__global const float *)((const __global char *)src_void+src_offset_bytes);\n"
                      " __global float *dst=(__global float *)((__global char *)dst_void+dst_offset_bytes);\n"
                      " const int row_id=get_group_id(0);\n"
                      " const int local_id=get_local_id(0);\n"
                      " __local float local_sum_sq[RMSNORM_WG_SIZE];\n"
                      " float thread_sum_sq=0.0f;\n"
                      " for (int i=local_id;i<D;i+=RMSNORM_WG_SIZE) {\n"
                      "  float val=src[row_id*D+i];\n"
                      "  thread_sum_sq+=val*val;\n"
                      " }\n"
                      " local_sum_sq[local_id]=thread_sum_sq;\n"
                      " barrier(CLK_LOCAL_MEM_FENCE);\n"
                      " for (int s=RMSNORM_WG_SIZE/2;s>0;s>>=1) {\n"
                      "  if (local_id<s) local_sum_sq[local_id]+=local_sum_sq[local_id+s];\n"
                      "  barrier(CLK_LOCAL_MEM_FENCE);\n"
                      " }\n"
                      " float rms_val;\n"
                      " if (local_id==0) {\n"
                      "  float variance=local_sum_sq[0]/D;\n"
                      "  rms_val=rsqrt(variance+epsilon);\n"
                      "  local_sum_sq[0]=rms_val;\n"
                      " }\n"
                      " barrier(CLK_LOCAL_MEM_FENCE);\n"
                      " rms_val=local_sum_sq[0];\n"
                      " for (int i=local_id;i<D;i+=RMSNORM_WG_SIZE) {\n"
                      "  float weight_val;\n"
                      "  if (weight_is_q4) {\n"
                      "   weight_val=dequantize_q4_0((const __global block_q4_0 *)weights,i);\n"
                      "  } else {\n"
                      "   weight_val=((const __global float *)weights)[i];\n"
                      "  }\n"
                      "  if (add_unit_offset) weight_val+=1.0f;\n"
                      "  size_t index=row_id*D+i;\n"
                      "  dst[index]=src[index]*rms_val*weight_val;\n"
                      " }\n"
                      "}\n"
                      "__kernel void rmsnorm_f16_q4(\n"
                      " __global const void *src_void,\n"
                      " __global void *dst_void,\n"
                      " __global const void *weights,\n"
                      " const int weight_is_q4,\n"
                      " const int D,\n"
                      " const float epsilon,\n"
                      " const int add_unit_offset,\n"
                      " const ulong src_offset_bytes,\n"
                      " const ulong dst_offset_bytes\n"
                      ") {\n"
                      " __global const half *src=(__global const half *)((const __global char *)src_void+src_offset_bytes);\n"
                      " __global half *dst=(__global half *)((__global char *)dst_void+dst_offset_bytes);\n"
                      " const int row_id=get_group_id(0);\n"
                      " const int local_id=get_local_id(0);\n"
                      " __local float local_sum_sq[RMSNORM_WG_SIZE];\n"
                      " float thread_sum_sq=0.0f;\n"
                      " for (int i=local_id;i<D;i+=RMSNORM_WG_SIZE) {\n"
                      "  float val=(float)src[row_id*D+i];\n"
                      "  thread_sum_sq+=val*val;\n"
                      " }\n"
                      " local_sum_sq[local_id]=thread_sum_sq;\n"
                      " barrier(CLK_LOCAL_MEM_FENCE);\n"
                      " for (int s=RMSNORM_WG_SIZE/2;s>0;s>>=1) {\n"
                      "  if (local_id<s) local_sum_sq[local_id]+=local_sum_sq[local_id+s];\n"
                      "  barrier(CLK_LOCAL_MEM_FENCE);\n"
                      " }\n"
                      " float rms_val;\n"
                      " if (local_id==0) {\n"
                      "  float variance=local_sum_sq[0]/D;\n"
                      "  rms_val=rsqrt(variance+epsilon);\n"
                      "  local_sum_sq[0]=rms_val;\n"
                      " }\n"
                      " barrier(CLK_LOCAL_MEM_FENCE);\n"
                      " rms_val=local_sum_sq[0];\n"
                      " for (int i=local_id;i<D;i+=RMSNORM_WG_SIZE) {\n"
                      "  float weight_val;\n"
                      "  if (weight_is_q4) {\n"
                      "   weight_val=dequantize_q4_0((const __global block_q4_0 *)weights,i);\n"
                      "  } else {\n"
                      "   weight_val=((const __global float *)weights)[i];\n"
                      "  }\n"
                      "  if (add_unit_offset) weight_val+=1.0f;\n"
                      "  size_t index=row_id*D+i;\n"
                      "  float src_val=(float)src[index];\n"
                      "  dst[index]=(half)(src_val*rms_val*weight_val);\n"
                      " }\n"
                      "}\n";
}  // namespace mllm::opencl
