if(MLLM_BUILD_OPENCL_BACKEND)
  add_executable(mllm-bsa-twopass-bench main.cpp)
  target_link_libraries(mllm-bsa-twopass-bench PRIVATE MllmRT MllmCPUBackend MllmOpenCLBackend)
  target_include_directories(mllm-bsa-twopass-bench PRIVATE ${MLLM_INCLUDE_DIR})
  target_include_directories(mllm-bsa-twopass-bench PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
endif()
